### ISSUE TITLE
Normalizing embeddings before cross validation?

### ISSUE THREAD

**Issue by Linlinzhao** [jrwnter/cddd#10]
In the demo script, embeddings are normalized before feeding into svm models. By doing that, the CV performance might be an overestimate for generalizability, see [here](https://stats.stackexchange.com/questions/77350/perform-feature-normalization-before-or-within-model-validation) and [here](https://stats.stackexchange.com/questions/327294/data-standardization-for-training-and-testing-sets-for-different-scenarios)

**Comment by jrwnter** [comment]
Hi, 
good catch. Indeed, you should not normalize by the combined statistics of train and test fold but only by the train fold. But the demo script is just a quick test if the model runs on your environment and produces similar results.
