### ISSUE TITLE
What is your objectives (properties) for the classification model used to train the encoder?

### ISSUE THREAD

**Issue by CandyClass** [jrwnter/cddd#28]
In your model there is a 3 layer FC model trained to predict "some" properties to make the latent representation consist of more information, but it seems that you haven't describe what properties excactly you used in this process. I wonder are they logP/QED/SA as described in Gómez-Bombarelli's work (for you are training in ZINC as well), or are they logP/partial charge/valence electrons/... as you described in the preprocessing section which extracted for each molecule?

**Comment by lianghsun** [comment]
The descriptors used in this paper should be found within this segment of [code](https://github.com/jrwnter/cddd/blob/8c1f90d1d927962658be6b9086f2cb5fa3403ae9/cddd/preprocessing.py#L164f).

https://github.com/jrwnter/cddd/blob/8c1f90d1d927962658be6b9086f2cb5fa3403ae9/cddd/preprocessing.py#L164C1-L175C31
