### ISSUE TITLE
can't install tensorflow-gpu

### ISSUE THREAD

**Issue by xuzhang5788** [jrwnter/cddd#4]
I followed your instruction to install TensorFlow-gpu. After pip install ...., I didn't get any error messages. However, when I import TensorFlow, I got a page of error messages. I tried to use conda to install TensorFlow-gpu, it still didn't work. 
Tensorflow-cpu works.

**Comment by jrwnter** [comment]
Hmm, sounds like an issue with nvidia-drivers. Can you check if you have the right drivers installed for the recommended tf-version?
