### ISSUE TITLE
How do you tokenize the SMILES representation?

### ISSUE THREAD

**Issue by Dinxin** [jrwnter/cddd#5]

**Comment by jrwnter** [comment]
Tokenization is done here: [https://github.com/jrwnter/cddd/blob/8c1f90d1d927962658be6b9086f2cb5fa3403ae9/cddd/input_pipeline.py#L139](url)
The SMILES string is basically splitted in individual characters such as C,N,Cl,1,[, etc. Each of this characters is one-hot encoded.
