### ISSUE TITLE
Prepare raw data for retrain

### ISSUE THREAD

**Issue by Minys233** [jrwnter/cddd#7]
This is a great work with well documented code (rare)! 

Here I'm trying to retrain this model on the same data in the paper. The paper mentioned that the training data is from PubChem and ZINC15: *After applying this preprocessing procedure the resulting dataset consisted of approximately **72 million** compounds.* 

I started from ZINC15 and PubChem raw data and find that the number of molecules after preprocessing is far more than 72 million, up to tens of GBytes! So I'm curious about how do you prepare raw data before preprocessing? 

Here is what I did:
 - **ZINC15**: download from [ZINC tranches](http://zinc15.docking.org/tranches/home/), with default config, which are `Rep.: 2D`, `React.: Standard`, `Purch.: Wait OK`, total 1285M substances (far more than 72 million even after preprocessing).
- **PubChem**: download all SDF files from PubChem compound: ftp://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/

Thank you so much for your patience!

**Comment by jrwnter** [comment]
Hi,
yes, this is a "known issue"... I unfortunately refered to the wrong ZINC version. I actually used the much smaller ZINC12 databse (~40 million i think). Sorry for that. 
It would be interesting to see if including all compounds of ZINC15 has an impact on the descriptive power of the descriptors. Although, in my studies I had the impression that including more compounds had no such impact.

**Comment by Minys233** [comment]
Thank you so much for explanation!
